---
- type: cluster
  name: Zookeeper cluster
  description: Zookeeper cluster software
  version: 0.0.1
  edition: community
  license: EULA.txt
  adcm_min_version: 2022.10.04.17

  upgrade:
    - name: 0.0.2 community
      versions:
        min: "0.0.1"
        max_strict: "1.0.0"
      from_edition: ["community"]
      states:
        available: any
        on_success: upgrade

  config:
    - name: __main_info
      type: file
      default: "info/cluster.html"

    - name: cluster_name
      type: string
      default: "Teach cluster"

  actions:
    install:
      display_name: "Install"
      type: task
      allow_to_terminate: true
      scripts:
        # TODO: тут можно сократить количество задач без потери смысла
        # применив практики из Ansible
        # The pre_tasks keyword just lets you list tasks to run before the roles are called.
        # https://docs.ansible.com/ansible/latest/playbook_guide/guide_rolling_upgrade.html
        # pre_tasks выполнить сбор необходимых фактов из ADCM и задействованных серверов
        - name: preinstall
          display_name: "Preinstall"
          script_type: ansible
          script: ansible/cluster_preinstall.yaml
          params:
            ansible_tags: preinstall, service_dependency_check
        - name: zookeeper
          display_name: "Zookeeper"
          script_type: ansible
          script: ansible/zookeeper.yml
          params:
            ansible_tags: install, configure, start
        # TODO: Добавить обработку (сохранене данных adcm_config),
        # выполнить проверку логов (adcm_check)
        # которые произошли в результате инсталляции zookeeeper
        # выделение в отдельный стек задач в виде post_tasks позволит структурироать
        # код, а так же поддерживает принцип единственной ответственности
      states:
        available:
          - created
          - faulty_installed
        on_success: created
        on_fail: faulty_installed
