---
- type: cluster
  name: Zookeeper cluster
  description: Zookeeper cluster software
  version: 0.0.1
  edition: community
  license: EULA.txt
  adcm_min_version: 2022.10.04.17

  upgrade:
    - name: 0.0.2 community
      versions:
        min: "0.0.1"
        max_strict: "1.0.0"
      from_edition: ["community"]
      states:
        available: any
        on_success: upgrade

  config:
    - name: __main_info
      type: file
      default: "info/cluster.html"

    - name: cluster_name
      type: string
      default: "Teach cluster"

  actions:
    install:
      display_name: "Install"
      type: task
      allow_to_terminate: true
      scripts:
        - name: Install cluster
          display_name: "Install cluster"
          script_type: ansible
          script: ansible/install_cluster.yaml
      states:
        available:
          - created
          - faulty_installed
        on_success: created
        on_fail: faulty_installed

- type: service
  name: zookeeper
  display_name: Zookeeper
  version: 3.9.1

  export:
    - Main

  config:
    - name: Main
      type: group
      subs:
        - name: connect
          type: string
          read_only: any
          required: no
          description: >
            Zookeeper connection string that is used by other services or clusters.
            It is generated automatically.

        - name: data_dirs
          display_name: dataDir
          type: string
          default: "/var/lib/zookeeper"
          description: >
            The location where Zookeeper stores the in-memory database snapshots and,
            unless specified otherwise, the transaction log of updates to the database.
            Specified as the dataDir parameter in the zoo.cfg configuration file.
  actions:
    Start:
      type: job
      script_type: ansible
      script: ./ansible/zookeeper_server.yml
      # TDDO: прогон конфигурации сервера
      states:
        available:
          - installed

  # components:
  #   SERVER:
  #     display_name: Zookeeper Server
  #     constraint: [odd]
  #     actions:
  #       Start:
  #         type: job
  #         script_type: ansible
  #         script: ./ansible/zookeeper_server.yml
  #         states:
  #           available:
  #             - installed