---
- type: cluster
  name: Zookeeper cluster
  description: Zookeeper cluster software
  version: 0.0.1
  edition: community
  license: EULA.txt
  adcm_min_version: 2022.10.04.17

  upgrade:
    - name: 0.0.2 community
      versions:
        min: "0.0.1"
        max_strict: "1.0.0"
      from_edition: ["community"]
      states:
        available: any
        on_success: upgrade

  config:
    - name: __main_info
      type: file
      default: "info/cluster.html"

    - name: cluster_name
      type: string
      default: "Teach cluster"

    - name: zk_0
      type: string
      display_name: "zk 0"
      required: False

    - name: zk_1
      type: string
      display_name: "zk 1"
      required: False

    - name: zk_2
      type: string
      display_name: "zk 2"
      required: False

  actions:
    install:
      display_name: "Install"
      type: task
      allow_to_terminate: true
      scripts:
        - name: Install cluster
          display_name: "Install cluster"
          script_type: ansible
          script: ansible/install_cluster.yaml
      states:
        available:
          - created
          - faulty_installed
        on_success: created
        on_fail: faulty_installed
