---
- name: Check cluster
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - fail:
        msg: "there are no hosts in the cluster"
      when: groups['CLUSTER'] | length == 0

- name: Run repos
  hosts: CLUSTER
  gather_facts: false
  pre_tasks:
    - name: "New cluster pre_tasks"
      debug:
        msg: "This Preinstall Cluster"

  tasks:
    - set_fact:
        save_to_adcm_prepared_data: >
          {{
            cluster.config | combine({'cluster_name': 'YOUHOOO'},recursive=True)
          }}

  post_tasks:
    - import_tasks: lib/tasks_save_to_adcm.yaml

  vars:
    save_to_adcm_prepared_data: {}
    # 'cluster', 'service', 'component', 'host', 'hostprovider'
    save_to_adcm_type: "cluster"
    save_to_adcm_service_name: ""
    save_to_adcm_component_name: ""
    save_to_adcm_host_id: 0
