---

- import_playbook: lib/check_cluster_hosts.yaml
  vars:
    group_name: CLUSTER
    type_name: Cluster

- name: Cluster install
  hosts: CLUSTER
  gather_facts: false
  pre_tasks:
    - debug:
        msg: "PRE-TASKS install cluster"

  tasks:
    - set_fact:
        save_to_adcm_prepared_data: >
          {{
            cluster.config | combine({'cluster_name': 'YOUHOOO'},recursive=True)
          }}

  post_tasks:
    - import_tasks: lib/tasks_save_to_adcm.yaml

  vars:
    save_to_adcm_prepared_data: {}
    # 'cluster', 'service', 'component', 'host', 'hostprovider'
    save_to_adcm_type: "cluster"
    save_to_adcm_service_name: ""
    save_to_adcm_component_name: ""
    save_to_adcm_host_id: 0
