---

- import_playbook: lib/check_cluster_hosts.yaml
  vars:
    group_name: CLUSTER
    type_name: Cluster

- name: Install zookeeper
  hosts: CLUSTER
  gather_facts: false
  pre_tasks:
    - debug:
        msg:
          - "PRE-TASKS zookeeper"
          - "{{ vars }}"

  roles:
    - role: java
    - role: zookeeper

  post_tasks:
    - import_tasks: lib/tasks_save_to_adcm.yaml
  vars:
    save_to_adcm_prepared_data: {}
    # 'cluster', 'service', 'component', 'host', 'hostprovider'
    save_to_adcm_type: "service"
    save_to_adcm_service_name: "zookeeper"
    save_to_adcm_component_name: ""
    save_to_adcm_host_id: 0
